additionalProperties:
  key:    #The application of the application is limited to English, used to create a folder in Linux
  name:   #Application name
  tags:
    - Tool #Application tags, you can have multiple, please refer to the label list below
  shortDescZh:  #Application Chinese description, do not exceed 30 words
  shortDescEn:  #Application English description
  type: tool  #Application type, different from the application classification, can only have one, please refer to the type list below
  crossVersionUpdate:   #Can it be upgraded across the large version
  limit:  #Application installation quantity limit, 0 Represents unlimited
  website:  #Official website address
  github:  #github address
  document:  #Document address