version: "3"
services:
  nextweb:
    container_name: nextweb
    restart: always
    ports:
      - 10086:10086
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /opt:/opt
      - /root:/root
    environment:
      - TZ=Asia/Ho_Chi_Minh
    image: nextweb:latest
    labels:
      createdBy: "Apps"

